import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/toggler";
import { HeroHeader } from "@/components/entete";
import { FooterSection } from "@/components/basDePage";
import "./globals.css";
import CsrfUtils from "@/components/utils/csrf_utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <CsrfUtils />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <HeroHeader />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
