# Generated by Django 5.1.7 on 2025-03-26 20:41

import djongo.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='favoris',
            field=djongo.models.fields.JSONField(null=True),
        ),
    ]
