# Generated by Django 5.1.6 on 2025-02-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Adresse',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='mot_de_pass',
            new_name='mot_de_passe',
        ),
    ]
