# Generated by Django 5.1.6 on 2025-02-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_adress_adresse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='mot_de_passe',
            new_name='mot_de_pass',
        ),
    ]
