# Generated by Django 5.1.6 on 2025-02-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_adress_adresse_and_more'),
        ('home', '0004_rename_mot_de_pass_utilisateur_mot_de_passe'),
    ]

    operations = [
    ]
